#!/bin/bash

newgit="eval"
if [[ "`lsb_release -rs`" =~ ^7\. ]]; then
    newgit="scl enable rh-git218"
fi
for N in 1 2 3; do
    for V in plugin${N}_name plugin${N}_version; do
        eval "`sed -n "s/^%define $V /$V=/p" rpm/htvault-config.spec`"
    done

    eval plugin${N}_prefix=v
    eval plugin_version=\${plugin${N}_version}
    if [[ "$plugin_version" == commit/* ]]; then
        eval plugin${N}_prefix=""
        eval plugin${N}_version=\${plugin_version#commit/}
    fi
done

BASE=htvault-config-src
GO116="`ls -d $HOME/go1.16.* 2>/dev/null|tail -1`"
set -ex
if [ -n "$GO116" ]; then
    PATH="$GO116/bin:$PATH"
fi

cd "`dirname $0`"
for OLDBASE in $BASE-*; do
    if [ -d $OLDBASE/gopath ]; then
	# this is in case it wasn't fully created and chmodded
        GOPATH=$PWD/$OLDBASE/gopath go clean -modcache
    fi
done
rm -rf $BASE-*
BASE="$BASE-`sed -n 's/^%define tarball_version //p' rpm/htvault-config.spec`"
mkdir $BASE
cd $BASE
mkdir gopath
export GOPATH=$PWD/gopath
curl -s https://codeload.github.com/hashicorp/${plugin1_name}/tar.gz/${plugin1_prefix}${plugin1_version} | tar xzf -
cd ${plugin1_name}-${plugin1_version}
curl -sL https://github.com/hashicorp/$plugin1_name/pull/119.diff | patch -p1
curl -sL https://github.com/hashicorp/$plugin1_name/pull/131.diff | patch -p1
$newgit "make bootstrap"
go mod vendor
cd ..

curl -s https://codeload.github.com/42wim/${plugin2_name}/tar.gz/${plugin2_prefix}${plugin2_version} | tar xzf -
cd ${plugin2_name}-${plugin2_version}
go mod vendor
cd ..

curl -s https://codeload.github.com/puppetlabs/${plugin3_name}/tar.gz/${plugin3_prefix}${plugin3_version} | tar xzf -
cd ${plugin3_name}-${plugin3_version}
curl -sL https://github.com/puppetlabs/$plugin3_name/pull/41.diff | patch -p1
$newgit "make generate"
go mod vendor
cd ..
cd ..

rm -rf $GOPATH/pkg/mod/cache/vcs
find $GOPATH/pkg/mod -type d ! -perm -200|xargs chmod u+w
tar --exclude .git -czf $BASE.tar.gz $BASE
rm -rf $BASE
