#!/bin/bash

# use $TMPDIR as temporary space for improved performance

for N in 1 2; do
    for V in plugin${N}_name plugin${N}_version; do
        eval "`sed -n "s/^%define $V /$V=/p" rpm/htvault-config.spec`"
    done

    eval plugin${N}_prefix=v
    eval plugin_version=\${plugin${N}_version}
    if [[ "$plugin_version" == commit/* ]]; then
        eval plugin${N}_prefix=""
        eval plugin${N}_version=\${plugin_version#commit/}
    fi
done
V=gox_version
eval "`sed -n "s/^%define $V /$V=/p" rpm/htvault-config.spec`"

BASE=htvault-config-src
set -ex

cd "`dirname $0`"
HERE=$PWD
cd ${TMPDIR:-/tmp}

for OLDBASE in $BASE-*; do
    if [ -d $OLDBASE/gopath ]; then
	# this is in case it wasn't fully created and chmodded
        GOPATH=$PWD/$OLDBASE/gopath go clean -modcache
    fi
done
rm -rf $BASE-*
BASE="$BASE-`sed -n 's/^%define tarball_version //p' $HERE/rpm/htvault-config.spec`"
mkdir $BASE
cd $BASE
mkdir gopath
export GOPATH=$PWD/gopath

# do the install for its side effects of caching the source files
go install github.com/mitchellh/gox@v$gox_version
rm -f $GOPATH/bin/gox

curl -s https://codeload.github.com/42wim/${plugin1_name}/tar.gz/${plugin1_prefix}${plugin1_version} | tar xzf -
cd ${plugin1_name}-${plugin1_version}
go mod vendor
cd ..

curl -s https://codeload.github.com/openbao/${plugin2_name}/tar.gz/${plugin2_prefix}${plugin2_version} | tar xzf -
cd ${plugin2_name}-${plugin2_version}
go mod vendor
make generate
cd ..
cd ..
rm -rf $GOPATH/pkg/mod/cache/vcs
find $GOPATH/pkg/mod -type d ! -perm -200 -print0|xargs -0 -r chmod u+w
tar --exclude .git -czf $HERE/$BASE.tar.gz $BASE
rm -rf $BASE
